#pragma once

#include <Arduino.h>

#ifndef HAB_WSPR_AUTHORISED
#define HAB_WSPR_AUTHORISED 0
#endif

#ifndef HAB_WSPR_BASE_FREQUENCY_CENTIHZ
#define HAB_WSPR_BASE_FREQUENCY_CENTIHZ 0ULL
#endif

#ifndef HAB_WSPR_POWER_DBM
#define HAB_WSPR_POWER_DBM 10
#endif

#ifndef HAB_SI5351_CORRECTION_PPB
#define HAB_SI5351_CORRECTION_PPB 0
#endif

#ifndef HAB_LORAWAN_POLICY_REVIEWED
#define HAB_LORAWAN_POLICY_REVIEWED 0
#endif

constexpr char HAB_WSPR_CALLSIGN[] = "M7CWV";
constexpr uint32_t HAB_SI5351_REFERENCE_HZ = 26000000UL;
constexpr uint32_t HAB_IMAGE_INTERVAL_SECONDS = 8UL * 60UL * 60UL;
constexpr uint32_t HAB_CAPTURE_RETRY_MS = 30UL * 60UL * 1000UL;
constexpr uint32_t HAB_NETWORK_EVIDENCE_TIMEOUT_MS = 2UL * 60UL * 60UL * 1000UL;
constexpr uint32_t HAB_WATCHDOG_TIMEOUT_SECONDS = 180UL;
